# Generated by Django 2.0.3 on 2018-03-28 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saisiecontrat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='courriel',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='alternant',
            name='adresse1representant',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='alternant',
            name='adresse2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='alternant',
            name='adresse2representant',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='alternant',
            name='codepostalrepresentant',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='alternant',
            name='courriel',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='alternant',
            name='nomrepresentant',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AlterField(
            model_name='alternant',
            name='prenomrepresentant',
            field=models.CharField(blank=True, max_length=35),
        ),
        migrations.AlterField(
            model_name='alternant',
            name='villerepresentant',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='cfa',
            name='adresse2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='dateexportationCFA',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='dategenerationCERFA',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='datemaj',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='datesaisiecomplete',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='detamajmission',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='logement',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='nourriture',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='primepanier',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='adresse2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='codeconventioncollective',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='libelleconventioncollective',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='telecopie',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='formation',
            name='an2au',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='formation',
            name='an2du',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='formation',
            name='an3au',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='formation',
            name='an3du',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='formation',
            name='heuresan2',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='formation',
            name='heuresan3',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='remuneration',
            name='anper2au',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='remuneration',
            name='anper2base',
            field=models.CharField(blank=True, choices=[(1, 'SMIC'), (2, 'SMC')], max_length=4),
        ),
        migrations.AlterField(
            model_name='remuneration',
            name='anper2du',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='remuneration',
            name='anper2taux',
            field=models.FloatField(blank=True),
        ),
    ]
