# Generated by Django 2.0.3 on 2018-03-28 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saisiecontrat', '0002_auto_20180328_2217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alternant',
            name='codeINSEEcommuneNaissance',
        ),
        migrations.AddField(
            model_name='alternant',
            name='communeNaissance',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
