# Generated by Django 2.0.3 on 2018-03-28 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saisiecontrat', '0003_auto_20180328_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrat',
            name='alternant',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='saisiecontrat.Alternant'),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='caisseretraitecomplementaire',
            field=models.CharField(blank=True, max_length=35),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='datedebutcontrat',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='dateeffetavenant',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='dateembauche',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='datefincontrat',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='dateinscription',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='dureehebdomadairetravail',
            field=models.DurationField(blank=True),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='entreprise',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='saisiecontrat.Entreprise'),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='faita',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='faitle',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='formation',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='saisiecontrat.Formation'),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='mission',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='numeroanneedebutcontrat',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='numerocontratanterieur',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='salairebrutmensuel',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='salaireminimumconventionnel',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='typederogation',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(11, 'Age de l’apprenti inférieur à 16 ans'), (12, 'Age supérieur à 25 ans : cas spécifiques prévus dans le code du travail'), (21, 'Réduction de la durée du contrat ou de la période d’apprentissage'), (22, 'Allongement  de la durée du contrat ou de la période d’apprentissage'), (31, 'Début de l’apprentissage hors période légale (plus de 3 mois avant ou après la date de début du cycle de formation)'), (40, 'Troisième contrat pour une formation de même niveau'), (50, 'Cumul de dérogations'), (60, 'Autre dérogation')]),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='datemaj',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='datemajcontacts',
            field=models.DateTimeField(blank=True),
        ),
    ]
